[package]
name = "rint-rust-kernel"
version = "0.1.0"
edition = "2024"

[dependencies]

[workspace]
members = [
    "kernel",
    "crates/hal",
    "crates/scheduler",
    "crates/metrics",
    "crates/sched-sim",
    "arch-x86_64",
    "arch-riscv64",
]
resolver = "2"
